id: web-prometheus
info:
  tags: application
  reference:
    - https://prometheus.io/
  name: prometheus
  author: archer
  verified: false
  description: 用于指标采集、时序数据查询与告警的监控系统。
  created: 2025/04/24
rules:
  r0:
    request:
      method: GET
      path: /
    expression: response.status == 200 && response.body.ibcontains(b"<title>Prometheus")
expression: r0()
