// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/",
        "contact": {
            "name": "zhizhuo",
            "url": "https://github.com/"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/cel/evaluate": {
            "post": {
                "security": [
                    {
                        "ApiToken": []
                    }
                ],
                "description": "支持注入用户自定义变量后求值，便于快速验证 CEL 写法",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "finger"
                ],
                "summary": "CEL 表达式调试求值",
                "parameters": [
                    {
                        "description": "表达式 + 变量",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EvaluateCELInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.EvaluateCELOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/finger/run": {
            "post": {
                "security": [
                    {
                        "ApiToken": []
                    }
                ],
                "description": "返回每条 rule 的请求 / 响应 / CEL 结果以及最终表达式判定",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "finger"
                ],
                "summary": "逐 rule 执行 YAML 指纹",
                "parameters": [
                    {
                        "description": "运行参数",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RunFingerprintInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.RunFingerprintOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/library/default": {
            "get": {
                "security": [
                    {
                        "ApiToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "library"
                ],
                "summary": "查询默认指纹库目录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.DefaultLibraryDirOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/library/delete": {
            "delete": {
                "security": [
                    {
                        "ApiToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "library"
                ],
                "summary": "删除指定 YAML 文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "要删除的文件路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/library/list": {
            "get": {
                "security": [
                    {
                        "ApiToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "library"
                ],
                "summary": "列出指纹库下全部 yaml 文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "指纹库根目录，默认 fingerYaml/",
                        "name": "rootDir",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否解析每个文件的 outline",
                        "name": "includeOutline",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.FingerFileMeta"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/library/load": {
            "get": {
                "security": [
                    {
                        "ApiToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "library"
                ],
                "summary": "加载指定 YAML 文件内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "绝对或相对路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.LoadYAMLOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/library/save": {
            "post": {
                "security": [
                    {
                        "ApiToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "library"
                ],
                "summary": "保存 YAML 文件（写入前会先校验合法性）",
                "parameters": [
                    {
                        "description": "保存参数",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SaveYAMLInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/request/send": {
            "post": {
                "security": [
                    {
                        "ApiToken": []
                    }
                ],
                "description": "支持 URL 参数模式与原始 HTTP raw 报文模式，自动提取标题/Server/证书/favicon hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "request"
                ],
                "summary": "发送 HTTP 请求获取响应",
                "parameters": [
                    {
                        "description": "请求选项",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SendRequestInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.SendRequestOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/yaml/validate": {
            "post": {
                "security": [
                    {
                        "ApiToken": []
                    }
                ],
                "description": "返回是否合法、错误位置（行号 / 列号）以及 finger 概要",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "yaml"
                ],
                "summary": "校验指纹 YAML 并提取概要",
                "parameters": [
                    {
                        "description": "YAML 内容",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ValidateYAMLInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.ValidateYAMLOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CertName": {
            "type": "object",
            "properties": {
                "commonName": {
                    "type": "string"
                },
                "country": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "locality": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "organization": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "organizationalUnit": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "province": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.CertSummary": {
            "type": "object",
            "properties": {
                "crlDistributionPoints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dnsNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "emailAddresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ipAddresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "issuer": {
                    "$ref": "#/definitions/model.CertName"
                },
                "issuerDN": {
                    "type": "string"
                },
                "notAfter": {
                    "type": "string"
                },
                "notBefore": {
                    "type": "string"
                },
                "ocspServer": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "publicKey": {
                    "type": "string"
                },
                "publicKeyAlgorithm": {
                    "type": "string"
                },
                "serialNumber": {
                    "type": "string"
                },
                "signatureAlgorithm": {
                    "type": "string"
                },
                "subject": {
                    "$ref": "#/definitions/model.CertName"
                },
                "subjectDN": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "model.DefaultLibraryDirOutput": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                }
            }
        },
        "model.EvaluateCELInput": {
            "type": "object",
            "properties": {
                "expression": {
                    "type": "string"
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "model.EvaluateCELOutput": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.FingerFileMeta": {
            "type": "object",
            "properties": {
                "modifiedAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "outline": {
                    "$ref": "#/definitions/model.FingerOutline"
                },
                "parseError": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "relPath": {
                    "type": "string"
                },
                "sizeBytes": {
                    "type": "integer"
                }
            }
        },
        "model.FingerOutline": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "expression": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ruleKeys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.RuleOutline"
                    }
                },
                "setVars": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "severity": {
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                }
            }
        },
        "model.LoadYAMLOutput": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "model.RequestMode": {
            "type": "string",
            "enum": [
                "url",
                "raw"
            ],
            "x-enum-varnames": [
                "RequestModeURL",
                "RequestModeRaw"
            ]
        },
        "model.RuleOutline": {
            "type": "object",
            "properties": {
                "expression": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.RuleRun": {
            "type": "object",
            "properties": {
                "celError": {
                    "type": "string"
                },
                "expression": {
                    "type": "string"
                },
                "httpError": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "latency": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "nonBoolResult": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "requestRaw": {
                    "type": "string"
                },
                "responseRaw": {
                    "type": "string"
                },
                "result": {
                    "type": "boolean"
                },
                "statusCode": {
                    "type": "integer"
                },
                "urlEvaluated": {
                    "type": "string"
                }
            }
        },
        "model.RunFingerprintInput": {
            "type": "object",
            "properties": {
                "followRedirects": {
                    "type": "boolean"
                },
                "proxy": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "timeoutSeconds": {
                    "type": "integer"
                },
                "useTls": {
                    "type": "boolean"
                },
                "verifyTls": {
                    "type": "boolean"
                },
                "yaml": {
                    "type": "string"
                }
            }
        },
        "model.RunFingerprintOutput": {
            "type": "object",
            "properties": {
                "expressionError": {
                    "type": "string"
                },
                "finalExpression": {
                    "type": "string"
                },
                "finalResult": {
                    "type": "boolean"
                },
                "fingerOutline": {
                    "$ref": "#/definitions/model.FingerOutline"
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.RuleRun"
                    }
                },
                "variables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.VarEntry"
                    }
                }
            }
        },
        "model.SaveYAMLInput": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "model.SendRequestInput": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "followRedirects": {
                    "type": "boolean",
                    "example": true
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "type": "string",
                    "example": "GET"
                },
                "mode": {
                    "enum": [
                        "url",
                        "raw"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.RequestMode"
                        }
                    ],
                    "example": "url"
                },
                "proxy": {
                    "type": "string"
                },
                "raw": {
                    "type": "string"
                },
                "target": {
                    "type": "string",
                    "example": "https://example.com"
                },
                "timeoutSeconds": {
                    "type": "integer",
                    "example": 10
                },
                "useTls": {
                    "type": "boolean",
                    "example": true
                },
                "verifyTls": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "model.SendRequestOutput": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "bodyBytes": {
                    "type": "integer"
                },
                "bodyIsBase64": {
                    "type": "boolean"
                },
                "certs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CertSummary"
                    }
                },
                "finalUrl": {
                    "type": "string"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "iconHash": {
                    "type": "string"
                },
                "latency": {
                    "type": "integer"
                },
                "rawHeader": {
                    "type": "string"
                },
                "requestRaw": {
                    "type": "string"
                },
                "server": {
                    "type": "string"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                },
                "statusText": {
                    "type": "string",
                    "example": "200 OK"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.ValidateYAMLInput": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "model.ValidateYAMLOutput": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.YAMLValidationError"
                    }
                },
                "outline": {
                    "$ref": "#/definitions/model.FingerOutline"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "model.VarEntry": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "model.YAMLValidationError": {
            "type": "object",
            "properties": {
                "column": {
                    "type": "integer"
                },
                "line": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "response.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiToken": {
            "description": "输入 Bearer 和当前会话令牌。",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GXX IDE API",
	Description:      "GXX 指纹规则编辑器 HTTP API：提供请求测试、YAML 校验、指纹运行、CEL 调试、指纹库 CRUD 能力。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
